In [306]:
import numpy as np
import matplotlib.pyplot as plt
from sympy.interactive.printing import init_printing

init_printing(use_unicode=False, wrap_line=False)
import sympy as smp

In [307]:
P, L, A, E, EI = smp.symbols('P L A E EI', real = True)


In [308]:
no_of_spans = int(input("Enter the number of spans:"))
print(no_of_spans)

4


In [309]:
span_lengths = np.zeros(no_of_spans)
print(span_lengths)
for i in range(len(span_lengths)):
    span_lengths[i]=input("Enter span length:")
print(span_lengths, type(span_lengths[0]))

[0. 0. 0. 0.]
[5. 7. 3. 4.] <class 'numpy.float64'>


In [310]:
# print("Enter dimensions of the beam:")
# h = float(input("Height of the beam in meters:"))
# b = float(input("Width of the beam in meters:"))

In [311]:
# gamma_concrete = 25
# g_beam = round(np.sum(span_lengths) * b * h * gamma_concrete,2)
# print(g_beam)
# q = 5
# g = 5

In [312]:
phi = np.zeros((no_of_spans - 1, no_of_spans-1))
print(phi)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [313]:
#Case A

In [314]:
phi0 = np.zeros((no_of_spans, 1))
phi0
print(phi0,len(phi0))
# X = np.array([[1, 1], [2, 2.5], [3, 1], [8, 7.5], [7, 9], [9, 9]])
# # print(X[:3, :])
# print(X,"\n",X[:, 0], X[:, 1])

[[0.]
 [0.]
 [0.]
 [0.]] 4


In [315]:
k = 0
for i in range(no_of_spans - 1):
    if i == 0 or i == no_of_spans - 2:
        if i == 0:
            print("f")
            phi0[i] = span_lengths[i] ** 3 / 24
            phi[i, 0] = (span_lengths[i] + span_lengths[i + 1]) / 3
            phi[i, 1] = span_lengths[i + 1] / 6
        if i == no_of_spans - 2:
            print("l")
            phi0[i] = span_lengths[i] ** 3 / 24
            phi0[i + 1] = span_lengths[i+1] ** 3 / 24
            phi[i, no_of_spans - 3] = span_lengths[i] / 6
            phi[i, no_of_spans - 2] = (span_lengths[i] + span_lengths[i + 1]) / 3
    else:
        print("m")
        phi0[i] = span_lengths[i] ** 3 / 24
        phi[i, k] = (span_lengths[i] / 6)
        phi[i, k + 1] = (span_lengths[i] + span_lengths[i + 1]) / 3
        phi[i, k + 2] = span_lengths[i + 1] / 6
        k += 1

print(phi, len(phi), "\n",phi0)

f
m
l
[[4.         1.16666667 0.        ]
 [1.16666667 3.33333333 0.5       ]
 [0.         0.5        2.33333333]] 3 
 [[ 5.20833333]
 [14.29166667]
 [ 1.125     ]
 [ 2.66666667]]


In [316]:
phi_P = np.zeros((no_of_spans - 1, 1))
print(phi_P)
p = np.empty(0)
p = np.append(p, np.zeros((no_of_spans - 1, 1)))
p = np.append(p, np.zeros((no_of_spans - 1, 1)))
print(p)

[[0.]
 [0.]
 [0.]]
[0. 0. 0. 0. 0. 0.]


In [317]:
out = np.zeros((no_of_spans - 1, 1))
print(out)
r = np.ones((no_of_spans - 1, 1))
print(r)
out = np.concatenate((out, r),axis=1)
print(out)

[[0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]]
[[0. 1.]
 [0. 1.]
 [0. 1.]]


In [318]:
k = 0
out = np.zeros((no_of_spans - 1, 1))
for i in range(no_of_spans):
    phi_P = np.zeros((no_of_spans - 1, 1))
    if i == 0 or i == no_of_spans - 1:
        if i == 0:
            phi_P[i] = phi0[i]
            out = out + np.linalg.inv(phi) @ -phi_P
        if i == no_of_spans - 1:
            phi_P[i - 1] = phi0[i]
            out = np.concatenate((out, np.linalg.inv(phi) @ -phi_P), axis=1)
    else:
        phi_P[k], phi_P[k + 1] = phi0[i], phi0[i]
        out = np.concatenate((out, np.linalg.inv(phi) @ -phi_P), axis=1)
        k += 1
        # print(phi_P)
# print(phi_P)
print(out)

[[-1.45561189 -2.54980234  0.08933482 -0.0577518 ]
 [ 0.52638364 -3.50782056 -0.30629082  0.19800619]
 [-0.11279649  0.75167583 -0.41650911 -1.18528704]]
